# Generated by Django 3.2.3 on 2021-06-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210606_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
