# Generated by Django 3.2.3 on 2021-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.CharField(max_length=100),
        ),
    ]
